# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
    paths:
      - coordinator/**
      - hls-encoder/**
      - rtmp-server/**
      - ws-stream-server/**
      - .github/workflows/go.yml
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.x

    - name: Build and test coordinator
      working-directory: ./coordinator
      run: go build . && go test -v

    - name: Build and test hls-encoder
      working-directory: ./hls-encoder
      run: go build . && go test -v

    - name: Build and test ws-stream-server
      working-directory: ./ws-stream-server
      run: go build . && go test -v
